package Ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;


public class home extends javax.swing.JFrame {

    
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        ImageIcon imgIc = new ImageIcon(getClass().getResource("../Imagenes/FLORES.png"));
        Image imgEs = imgIc.getImage().getScaledInstance(fondo.getWidth(),
                fondo.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEs = new ImageIcon(imgEs);
        fondo.setIcon(iconoEs);
        
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("../Imagenes/User.png"));
        Image imgEscalada = imgIcon.getImage().getScaledInstance(user.getWidth(),
                user.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        user.setIcon(iconoEscalado);
        
        ImageIcon imgIcono = new ImageIcon(getClass().getResource("../Imagenes/icons8-calculadora-30.png"));
        Image imgEscalad = imgIcono.getImage().getScaledInstance(calculadora.getWidth(),
                calculadora.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalad = new ImageIcon(imgEscalad);
        calculadora.setIcon(iconoEscalad);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel1 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        maestro = new javax.swing.JButton();
        panel4 = new javax.swing.JPanel();
        ventas = new javax.swing.JButton();
        panel5 = new javax.swing.JPanel();
        calculadora = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setOpaque(false);
        panel1.setPreferredSize(new java.awt.Dimension(200, 200));
        panel1.setLayout(new java.awt.BorderLayout());

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N
        panel1.add(user, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        jButton2.setText("jButton2");
        panel2.add(jButton2);

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 200, 800));

        panel3.setOpaque(false);
        panel3.setLayout(new java.awt.GridBagLayout());

        maestro.setBackground(new java.awt.Color(204, 0, 0));
        maestro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        maestro.setText("Maestro");
        panel3.add(maestro, new java.awt.GridBagConstraints());

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 200));

        panel4.setOpaque(false);
        panel4.setLayout(new java.awt.GridBagLayout());

        ventas.setBackground(new java.awt.Color(204, 0, 0));
        ventas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ventas.setText("Ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });
        panel4.add(ventas, new java.awt.GridBagConstraints());

        getContentPane().add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 200));

        panel5.setOpaque(false);
        panel5.setLayout(new java.awt.GridBagLayout());

        calculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-calculadora-30.png"))); // NOI18N
        calculadora.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 100;
        gridBagConstraints.gridheight = 100;
        panel5.add(calculadora, gridBagConstraints);

        getContentPane().add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 200, 200));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FLORES.png"))); // NOI18N
        fondo.setPreferredSize(new java.awt.Dimension(1200, 900));
        fondo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1112, 799));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calculadora;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton maestro;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JLabel user;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
